#!/usr/bin/env python3
"""Genera un script SQL de Postgres (esquema + datos + RLS) a partir de la
base de datos SQLite real del CRM, para migrar a Supabase. Solo lee SQLite."""
import sqlite3, os

DB = os.path.join(os.path.dirname(__file__), 'backend', 'data', 'crm.sqlite')
OUT = os.path.join(os.path.dirname(__file__), 'supabase_migration.sql')

# Tablas con id autoincremental
ID_TABLES = ['leads', 'clients', 'interactions', 'payments', 'tasks', 'affiliates']

def pgtype(sqlite_type, name, is_pk):
    t = (sqlite_type or '').upper()
    if is_pk:
        return 'bigint generated by default as identity primary key'
    if 'INT' in t:
        return 'bigint'
    if 'REAL' in t or 'FLOA' in t or 'DOUB' in t:
        return 'double precision'
    return 'text'

def lit(v):
    if v is None:
        return 'NULL'
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"

con = sqlite3.connect(DB)
con.row_factory = sqlite3.Row
cur = con.cursor()

out = []
out.append('-- Migración LogeCRM SQLite -> Supabase Postgres (generado)')
out.append('begin;')

for table in ID_TABLES:
    cols = cur.execute(f'PRAGMA table_info({table})').fetchall()
    if not cols:
        continue
    out.append(f'\ndrop table if exists public.{table} cascade;')
    defs = []
    for c in cols:
        defs.append(f'  "{c["name"]}" {pgtype(c["type"], c["name"], bool(c["pk"]))}')
    out.append(f'create table public.{table} (\n' + ',\n'.join(defs) + '\n);')
    # Datos
    rows = cur.execute(f'SELECT * FROM {table}').fetchall()
    colnames = [c['name'] for c in cols]
    for r in rows:
        vals = ', '.join(lit(r[cn]) for cn in colnames)
        collist = ', '.join(f'"{cn}"' for cn in colnames)
        out.append(f'insert into public.{table} ({collist}) values ({vals});')
    # Reset de la secuencia identity al max(id)
    out.append(
        f"select setval(pg_get_serial_sequence('public.{table}','id'), "
        f"coalesce((select max(id) from public.{table}),1), true);")

# settings (key/value, sin id)
scols = cur.execute('PRAGMA table_info(settings)').fetchall()
if scols:
    out.append('\ndrop table if exists public.settings cascade;')
    out.append('create table public.settings (\n  "key" text primary key,\n  "value" text\n);')
    for r in cur.execute('SELECT * FROM settings').fetchall():
        out.append(f"insert into public.settings (\"key\",\"value\") values ({lit(r['key'])}, {lit(r['value'])});")

# RLS: usuarios autenticados (edu/oscar) tienen acceso total
out.append('\n-- Row Level Security: acceso total para usuarios autenticados')
for table in ID_TABLES + ['settings']:
    out.append(f'alter table public.{table} enable row level security;')
    out.append(f'drop policy if exists "auth_full_access" on public.{table};')
    out.append(
        f'create policy "auth_full_access" on public.{table} '
        f'for all to authenticated using (true) with check (true);')

out.append('\ncommit;')

with open(OUT, 'w') as f:
    f.write('\n'.join(out) + '\n')

# Resumen
print('Generado:', OUT)
for table in ID_TABLES + ['settings']:
    try:
        n = cur.execute(f'SELECT count(*) FROM {table}').fetchone()[0]
        print(f'  {table}: {n} filas')
    except Exception:
        pass
con.close()
